---
- include: setup_essentials.yml

- name: "Setup prerequisites, mariadb, wkhtmltopdf, nodejs and psutil"
  hosts: localhost
  become: yes
  become_user: root
  vars:
    mysql_conf_tpl: ../files/mariadb_config.cnf
    mysql_secure_installation: True
  roles:
    - prerequisites
    - mariadb
    - wkhtmltopdf
    - nodejs
    - psutil

- name: setup bench and dev environment
  hosts: localhost
  vars:
    bench_repo_path: "/home/{{ ansible_user_id }}/.bench"
    bench_path: "/home/{{ ansible_user_id }}/{{ bench_name }}"
  tasks:
  # setup frappe-bench
  - include: includes/setup_bench.yml
    when: not run_travis and not without_bench_setup

  # setup development environment
  - include: includes/setup_dev_env.yml
    when: not run_travis and not production
