---
- include: setup_essentials.yml

- name: "Setup prerequisites, mariadb, wkhtmltopdf, nodejs and psutil"
  hosts: localhost
  become: yes
  become_user: root
  vars:
    bench_repo_path: "/home/{{ ansible_user_id }}/.bench"
    bench_path: "/home/{{ ansible_user_id }}/frappe-bench"
    mysql_conf_tpl: ../files/mariadb_config.cnf
    mysql_secure_installation: True
  roles:
    - prerequisites
    - mariadb
    - wkhtmltopdf
    - nodejs
    - psutil
  tasks:
  - debug:
      var: run_travis

  # setup frappe-bench
  - include: includes/setup_bench.yml
    when: not without_bench_setup and not run_travis

  # setup development environment
  - include: includes/setup_dev_env.yml
    when: not production and not run_travis and not without_bench_setup
