---
  # Install the common pre-requisites for the setting up bench
  - include: ../develop/install.yml

  #install production pre-requisites
  - name: Apply basic roles
    hosts: localhost
    become: yes
    become_user: root
    vars:
      - nginx_conf_file: files/nginx.conf
    roles:
      - locale
      - swap
      - logwatch
      - bash_screen_wall
      - frappe_selinux
      - dns_caching
      - ntpd
      - nginx
      - fail2ban
    tasks:
      - name: Set hostname
        hostname: name='{{ hostname }}'
        when: hostname is defined

      - name: Start NTPD
        service: name=ntpd state=started
        when: ansible_distribution == 'CentOS'

      - name: Start NTPD
        service: name=ntp state=started
        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include: includes/setup_inputrc.yml

  # Setup Bench for production environment
  - include: includes/setup_bench_production.yml
    when: not run_travis
